services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: VRuAd2Nvmp4ELHh5
      MONGO_INITDB_DATABASE: onboardingServiceDB
    volumes:
      - /tmp/mongo-data:/data/db
    networks:
      - mynetwork



networks:
  mynetwork:
    driver: bridge