server:
  port: 9090
  servlet:
    context-path: /api
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
         
# disable devtools
spring:
  application:
    name: EOnboardService
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9999/realms/OneShoot}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
  datasource:
    url: jdbc:mysql://localhost:3306/EOnboardServiceDB?useSSL=false&serverTimezone=GMT&createDatabaseIfNotExist=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  
